/* Pre  [:str].substring([:begin_index]).startsWith([:needle])        */
/* Post [:str].startsWith([:needle], [:begin_index])                  */
rewrite_node("simplify_calls_to_substring_and_startswith", id,
    cat(@node_to_string(code, str), ".startsWith(", @node_to_string(code, needle), ", ",
                                                    @node_to_string(code, begin_index), ")")
) :-
    method_invocation(id, subject, "startsWith", [needle, nil]),
    method_invocation(subject, str, "substring", [begin_index, nil]),
    source_code(_, code).
