/**
 * String.valueOf() should not be appended to a String
 * https://rules.sonarsource.com/java/RSPEC-1153
 */

/* Pre  String.valueOf([:x]) */
/* Post [:x] */
rewrite(1153, filename, right, arg_string) :-
    addition_expression(id, left, right),
    filename_of(id, filename),
    has_string_type(left),
    method_invocation(right, subject, "valueOf", [arg, nil]),
    string_representation(subject, "String"),
    string_representation(arg, arg_string).
