/**
 * Thread.run() should not be called directly
 * https://rules.sonarsource.com/java/RSPEC-1217
 */

/* Pre  [:x].run()   */
/* Post [:x].start() */
rewrite([1217, filename, start, end, cat(subject_str, ".start()")]) :-
    method_invocation(id, subject, "run", nil),
        filename_of(id, filename),
        starts_at(id, start),
        ends_at(id, end),
    has_thread_type(subject),
    string_representation(subject, subject_str).
