/**
 * Unused local variables should be removed
 * https://rules.sonarsource.com/java/RSPEC-1481
 */

/* Pre  [:local_var_decl] */
/* Post                   */
rewrite(1481, filename, start, end, "") :-
    local_variable_declaration_statement(id, declaration),
        filename_of(id, filename),
        starts_at(id, start),
        ends_at(id, end),
    local_variable_declaration(declaration, _, _, _),
    ! point_of_declaration(_, declaration).

