/**
 * Lambdas containing only one statement should not nest this statement in a
 * block
 * https://rules.sonarsource.com/java/RSPEC-1602
 */

/* Pre  [:lambda_params] -> { return [:x] } */
/* Post [:lambda_params] -> [:x] */
rewrite(1602, filename, lambda_body, expr_str) :-
    filename_of(lambda_expr, filename),
    lambda_expression(lambda_expr, _, lambda_body),
    block(lambda_body, [statement, nil]),
    return_statement(statement, expr),
    string_representation(expr, expr_str).

