/**
 * BigDecimal(double) should not be used
 * https://rules.sonarsource.com/java/RSPEC-2111
 */

rewrite(2111, filename, id, cat("BigDecimal.valueOf(", arg_str, ")")) :-
    class_instance_creation_expression(id, nil, nil, type, args, nil),
        filename_of(id, filename),
    args = [arg, nil],
    has_floating_point_type(arg),
    string_representation(type, "BigDecimal"),
    string_representation(arg, arg_str).
