/**
 * Unary prefix operators should not be repeated
 * https://rules.sonarsource.com/java/RSPEC-2761
 */

/* Pre  !![:x] */
/* Post [:x]   */
rewrite(1940, filename, start, end, expr_str) :-
    logical_complement_expression(id, sub),
        filename_of(id, filename),
        starts_at(id, start),
        ends_at(id, end),
    logical_complement_expression(sub, expr),
    string_representation(expr, expr_str).
