/**
 * Exceptions should not be created without being thrown
 * https://rules.sonarsource.com/java/RSPEC-3984
 */

rewrite(3984, filename, stmt, cat("throw ", stmt_str)) :-
    filename_of(stmt, filename),
    expression_statement(stmt, class_instance_creation),
    string_representation(stmt, stmt_str),
    class_instance_creation_expression(class_instance_creation, nil, _, type, _, _),
    is_exception_type(type).
