#include "nodes.dl"

/* Types
 ********************************/

.type id = [type: symbol, from: number, to: number]
.type id_list = [head: id, tail: id_list]
.type symbol_list = [head: symbol, tail: symbol_list]

/* Tokens
 ********************************/

.decl token(str: symbol, from: number, to: number)
.input token

/* AST nodes
 ********************************/

.decl root(id: id)
.input root
.output root(IO=stdout)

.decl ast_node(id: id)
ast_node(id) :- root(id).
ast_node(child) :- ast_node(ancestor), ancestor_of(ancestor, child).

.decl name_of(id: id, name: symbol)
name_of([name, A, B], name) :- ast_node([name, A, B]).

.decl starts_at(id: id, at: number)
starts_at([name, A, B], A) :- ast_node([name, A, B]).

.decl ends_at(id: id, at: number)
ends_at([name, A, B], B) :- ast_node([name, A, B]).

/* AST node relations
 ********************************/

.decl parent_of(parent: id, name: symbol, child: id)
.input parent_of

.decl parent_of_list(parent: id, name: symbol, children: id_list)
.input parent_of_list

/* transitive closure of parent_of and parent_of list */
.decl ancestor_of(ancestor: id, child: id)
ancestor_of(x, y) :-
    parent_of(x, _, y).
ancestor_of(x, z) :-
    ancestor_of(x, y),
    parent_of(y, _, z).
ancestor_of(x, y) :-
    parent_of_list(x, _, children),
    list_contains(children, y).
ancestor_of(x, z) :-
    ancestor_of(x, y),
    parent_of_list(y, _, children),
    list_contains(children, z).

.decl head_of(head: id, tail: id_list)
head_of(head, tail) :-
    parent_of_list(_, _, [head, tail]).
head_of(head, tail) :-
    head_of(_, [head, tail]).

/* is x at the position just before y in a list? */
.decl predecessor_of(x: id, y: id)
predecessor_of(x, y) :-
    head_of(x, [y, _]).

/* transitive closure of predecessor_of */
.decl precedes(x: id, y: id)
precedes(x, y) :-
    predecessor_of(x, y).
precedes(x, z) :-
    precedes(x, y),
    predecessor_of(y, z).

/* does the list contain the element? */
.decl list_contains(list: id_list, id: id)
list_contains([head,tail], head) :-
    parent_of_list(_, _, [head, tail]).
list_contains(list, b) :-
    list_contains(list, a),
    predecessor_of(a, b).

/* Common AST patterns
 ********************************/

.decl not_equals_null_expression(id: id, subject: id)
not_equals_null_expression(id, subject) :-
    not_equals_expression(id, _, _),
    parent_of(id, _, subject),
    parent_of(id, _, null),
    string_representation(null, "null"),
    subject != null.

/* Constant evaluation
 ********************************/

.decl evaluates_to_integer_value(id: id, value: number)
evaluates_to_integer_value(id, 0) :-
    integer_literal(id),
    string_representation(id, "0").
/* TODO
evaluates_to_integer_value(id, to_number(repr)) :-
    integer_literal(id),
    string_representation(id, repr).
*/
evaluates_to_integer_value(id, left_value + right_value) :-
    addition_expression(id, left, right),
    evaluates_to_integer_value(left, left_value),
    evaluates_to_integer_value(right, right_value).
evaluates_to_integer_value(id, left_value * right_value) :-
    multiplication_expression(id, left, right),
    evaluates_to_integer_value(left, left_value),
    evaluates_to_integer_value(right, right_value).
evaluates_to_integer_value(id, left_value - right_value) :-
    subtraction_expression(id, left, right),
    evaluates_to_integer_value(left, left_value),
    evaluates_to_integer_value(right, right_value).

.decl evaluates_to_boolean_value(id: id, value: number)
evaluates_to_boolean_value(id, 0) :-
    string_representation(id, "false").
evaluates_to_boolean_value(id, 1) :-
    string_representation(id, "true").
evaluates_to_boolean_value(id, left_value land right_value) :-
    conditional_and_expression(id, left, right),
    evaluates_to_boolean_value(left, left_value),
    evaluates_to_boolean_value(right, right_value).
evaluates_to_boolean_value(id, left_value lor right_value) :-
    conditional_or_expression(id, left, right),
    evaluates_to_boolean_value(left, left_value),
    evaluates_to_boolean_value(right, right_value).
evaluates_to_boolean_value(id, 1) :-
    equals_expression(id, left, right),
    evaluates_to_integer_value(left, x),
    evaluates_to_integer_value(right, x).
evaluates_to_boolean_value(id, 0) :-
    equals_expression(id, left, right),
    evaluates_to_integer_value(left, x),
    evaluates_to_integer_value(right, y),
    x != y.

/* String representation
 ********************************/

.decl source_code(str: symbol)
.input source_code

.decl string_representation(id: id, str: symbol)
string_representation([name, A, B], substr(code, A, B - A)) :-
    ast_node([name, A, B]),
    source_code(code).

/* Variable scope
 ********************************/

/**
 * The scope of a local variable declaration in a block (§14.2) is the rest of
 * the block in which the declaration appears, starting with its own
 * initializer (§14.4) and including any further declarators to the right in
 * the local variable declaration statement.
 * https://docs.oracle.com/javase/specs/jls/se6/html/statements.html
 */

.decl in_scope(position: id, identifier: symbol, type: id)
.output in_scope

/* Scope of variables is transitive (TODO: lambda is a special case?) */
in_scope(descendant, identifier, type) :-
    in_scope(ancestor, identifier, type),
    ancestor_of(ancestor, descendant).

/* Make parameter in enhanced for statement accessible in its body */
in_scope(body, identifier_str, stmt) :-
    ast_node(stmt),
    name_of(stmt, "enhanced_for_statement"),
    parent_of(stmt, "name", identifier),
    string_representation(identifier, identifier_str),
    parent_of(stmt, "statement", body).

/* Make field declarations in scope in the method bodies of their class */
in_scope(method_body, identifier_str, field) :-
    class_declaration(_, _, _, _, _, class_body),
    /* declared_at */
    list_contains(class_body, field),
    field_declaration(field, _, _, declarators),
    list_contains(declarators, declarator),
    variable_declarator(declarator, identifier, _),
    string_representation(identifier, identifier_str),
    /* available at */
    list_contains(class_body, method),
    method_declaration(method, _, _, method_body).

/* Make field declarations in scope in the constructor bodies of their class */
in_scope(constructor_body, identifier_str, field) :-
    class_declaration(_, _, _, _, _, class_body),
    /* declared_at */
    list_contains(class_body, field),
    field_declaration(field, _, _, declarators),
    list_contains(declarators, declarator),
    variable_declarator(declarator, identifier, _),
    string_representation(identifier, identifier_str),
    /* available at */
    list_contains(class_body, constructor),
    constructor_declaration(constructor, _, _, _, constructor_body).

/* Make formal parameters accessible in the body of a method */
in_scope(body, identifier_str, param) :-
    method_declaration(_, _, header, body),
    method_header(header, _, declarator, _),
    parent_of_list(declarator, "params", params),
    list_contains(params, param),
    formal_parameter(param, _, _, identifier),
    string_representation(identifier, identifier_str).

/* Make formal parameters accessible in the body of a constructor */
in_scope(body, identifier_str, param) :-
    constructor_declaration(_, _, declarator, _, body),
    parent_of_list(declarator, "params", params),
    list_contains(params, param),
    formal_parameter(param, _, _, identifier),
    string_representation(identifier, identifier_str).

/* Make local variable declarations accessible in the succeeding statements */
in_scope(succeeding_statement, identifier_str, declaration) :-
    local_variable_declaration_statement(declaration_statement, declaration),
    local_variable_declaration(declaration, _, declarators, _),
    precedes(declaration_statement, succeeding_statement),
    list_contains(declarators, declarator),
    variable_declarator(declarator, identifier, _),
    string_representation(identifier, identifier_str).

/* Point of declaration
 ********************************/

.decl point_of_declaration(id: id, declaration: id)
.output point_of_declaration(IO=stdout)
point_of_declaration(head, type) :-
    expression_name(id, [head, _]),
    in_scope(id, identifier, type),
    string_representation(head, identifier).

/* Types of variable references
 ********************************/

.decl has_type(id: id, type: id)
has_type(id, type) :-
    identifier(id),
    point_of_declaration(id, declpoint),
    parent_of(declpoint, "type", type).
/* If an expression_name only has one identifier, then the expression_name has the same
   type as the identifier */
has_type(exprname, type) :-
    expression_name(exprname, [head, nil]),
    has_type(head, type).

/* Type checking
 ********************************/

.decl collection_type_name(str: symbol)
collection_type_name("ArrayList").
collection_type_name("Collection").
collection_type_name("LinkedList").
collection_type_name("List").
collection_type_name("Queue").
collection_type_name("Set").
collection_type_name("SortedSet").
collection_type_name("Stack").
collection_type_name("Vector").

.decl floating_point_type_name(str: symbol)
floating_point_type_name("float").
floating_point_type_name("double").

.decl atomic_class_type_name(str: symbol)
atomic_class_type_name("AtomicInteger").
atomic_class_type_name("AtomicBoolean").
atomic_class_type_name("AtomicLong").

.decl boxed_type_name(str: symbol)
boxed_type_name("Boolean").
boxed_type_name("Byte").
boxed_type_name("Character").
boxed_type_name("Float").
boxed_type_name("Integer").
boxed_type_name("Long").
boxed_type_name("Short").
boxed_type_name("Double").

/* Is type */

.decl is_collection_type(id: id)
is_collection_type(id) :-
    // TODO: Should take imports into consideration?
    class_type(id, name, _, _),
    string_representation(name, name_str),
    collection_type_name(name_str).

.decl is_exception_type(id: id)
is_exception_type(id) :-
    class_type(id, name, _, _),
    string_representation(name, name_str),
    match(".*Exception", name_str).

.decl is_string_type(id: id)
is_string_type(id) :-
    class_type(id, name, _, _),
    string_representation(name, "String").

.decl is_boxed_type(id: id)
is_boxed_type(id) :-
    class_type(id, name, _, _),
    string_representation(name, name_str),
    boxed_type_name(name_str).

.decl is_floating_point_type(id: id)
is_floating_point_type(id) :-
    primitive_type(id, _, name),
    string_representation(name, name_str),
    floating_point_type_name(name_str).

.decl is_atomic_class_type(id: id)
is_atomic_class_type(id) :-
    class_type(id, name, _, _),
    string_representation(name, name_str),
    atomic_class_type_name(name_str).

.decl has_floating_point_type(id: id)
has_floating_point_type(id) :- floating_point_literal(id).
has_floating_point_type(id) :- has_type(id, type), is_floating_point_type(type).
has_floating_point_type(id) :-
    multiplication_expression(id, left, right),
    has_floating_point_type(left),
    has_floating_point_type(right).

.decl has_string_type(id: id)
has_string_type(id) :- string_literal(id).
has_string_type(id) :- has_type(id, type), is_string_type(type).

.decl has_string_or_boxed_type(id: id)
has_string_or_boxed_type(id) :- has_type(id, type), is_boxed_type(type).
has_string_or_boxed_type(id) :- has_string_type(id).

.decl has_collection_type(id: id)
has_collection_type(id) :- has_type(id, type), is_collection_type(type).

.decl has_atomic_class_type(id: id)
has_atomic_class_type(id) :- has_type(id, type), is_atomic_class_type(type).

/* Rewrite rules
 ********************************/

.decl rewrite(rule: number, message: symbol, from: id, to: symbol)
.output rewrite(IO=stdout)

//#include "rules/1132.dl"
//#include "rules/2204.dl"
//#include "rules/2272.dl"

#include "rules/1125_redundant_boolean.dl"
#include "rules/1155_use_isempty.dl"
#include "rules/1481_unused_local_variables.dl"
#include "rules/1596_fix_old_empty_collection.dl"
#include "rules/2095_close_resources.dl"
#include "rules/2111_bigdecimal_double.dl"
#include "rules/2293_diamond_operator.dl"
#include "rules/3984_throw_exceptions.dl"
#include "rules/4973_use_equals_method.dl"
