/* Pre  [:collection].removeAll([:collection]) */
/* Post [:collection].clear()         */
rewrite("S2114", filename, start, end, cat(collection_repr, ".clear()")) :-
    method_invocation(id, collection, "removeAll", [arg, nil]),
        filename_of(id, filename),
        starts_at(id, start),
        ends_at(id, end),
    has_collection_type(collection),
    string_representation(collection, collection_repr),
    string_representation(arg, collection_repr).
