/* Pre  new Integer([:argument]).toString() */
/* Post Integer.toString([:argument])       */
rewrite_node("simplify_calls_to_constructor_for_string_conversion", id, cat("Integer.toString(", arg_str, ")")) :-
    method_invocation(id, subject, "toString", nil),
    class_instance_creation_expression(subject, _, nil, type, [arg, nil], nil),
    string_representation(type, "Integer"),
    string_representation(arg, arg_str).
