/* Pre  new Integer([:argument]).toString() */
/* Post Integer.toString([:argument])       */
rewrite_node("simplify_calls_to_constructor_for_string_conversion", id,
    cat("Integer.toString(", @node_to_string(code, arg), ")")
) :-
    method_invocation(id, subject, "toString", nil),
    source_code(_, code),
    class_instance_creation_expression(subject, _, nil, type, [arg, nil], nil),
    ast_type_to_type(type, ["java.lang", "Integer", nil]).
