/* Pre  try {[:x]} finally {} */
/* Post [:x]                  */
replace_node_with_string("remove_redundant_try_blocks", id,
    @decrease_indentation(substr(code, body_start + 1, (body_end - 1) - (body_start + 1)))
) :-
    try_statement(id, body, nil, finally),
    source_code(_, code),
    parent_of(finally, "block", b),
    block(b, nil),
    starts_at(body, body_start),
    ends_at(body, body_end).
