rewrite("S1128", filename, start, end, "") :-
    import_declaration(id, specification),
        starts_at(id, start),
        ends_at(id, end),
        filename_of(id, filename),
    import_specification(specification, _, import),
    string_representation(import, import_str),
    count : { ast_node(other_id), filename_of(other_id, filename), string_representation(other_id, import_str) } = 1.   
