/**
 * BigDecimal(double) should not be used
 * https://rules.sonarsource.com/java/RSPEC-2111
 */

rewrite(2111, filename, start, end, cat("BigDecimal.valueOf(", arg_str, ")")) :-
    class_instance_creation_expression(id, nil, nil, type, args, nil),
        filename_of(id, filename),
        starts_at(id, start),
        ends_at(id, end),
    args = [arg, nil],
    has_floating_point_type(arg),
    string_representation(type, "BigDecimal"),
    string_representation(arg, arg_str).
