/* Pre  String.valueOf([:x]) */
/* Post [:x] */
rewrite("remove_unnecessary_calls_to_string_valueof", filename, start, end, arg_string) :-
    addition_expression(id, left, right),
        filename_of(id, filename),
    has_string_type(left),
    method_invocation(right, subject, "valueOf", [arg, nil]),
        starts_at(right, start),
        ends_at(right, end),
    string_representation(subject, "String"),
    string_representation(arg, arg_string).
