/* Pre  if ([:x]) {} */
/* Post {}           */
rewrite_node("remove_empty_if_statements", id, "{}") :-
    if_statement(id, _, body, nil),
    block(body, nil).

/* Pre  if ([:x]) {} else {[:y]} */
/* Post if (!([:x])) {[:y]}      */
rewrite_node("remove_empty_if_statements", id, cat("if (!(", cond_str, ")) ", else_str)) :-
    if_statement(id, cond, body, else),
    block(body, nil),
    block(else, _),
    string_representation(else, else_str),
    string_representation(cond, cond_str).
