/* Pre  if ([:x]) {} */
/* Post {}           */
rewrite_node("remove_empty_if_statements", id, "{}") :-
    if_statement(id, _, body, nil),
    block(body, nil).

/* Pre  if ([:x]) {} else {[:y]} */
/* Post if (!([:x])) {[:y]}      */
rewrite_node("remove_empty_if_statements", id,
    cat("if (!(", @node_to_string(code, cond), ")) ", @node_to_string(code, else))
) :-
    if_statement(id, cond, body, else),
    source_code(_, code),
    block(body, nil),
    block(else, _).
