/**
 * "BigDecimal(double)" should not be used
 *
 * https://rules.sonarsource.com/java/RSPEC-2111
 */

#define MESSAGE "Use \"BigDecimal.valueOf\" instead."

rewrite(MESSAGE, id, cat("BigDecimal.valueOf(", arg_str, ")")) :-
    class_instance_creation_expression(id, nil, type, args, nil),
    args = [arg, nil],
    has_floating_point_type(arg),
    string_representation(type, "BigDecimal"),
    string_representation(arg, arg_str).
