/**
 * ".equals()" should not be used to test the values of "Atomic" classes
 *
 * https://rules.sonarsource.com/java/RSPEC-2204
 */

rewrite(id, cat(left_str, " == ", right_str)) :-
    method_invocation(id, left, method, [right, nil]),
    has_atomic_class_type(left),
    has_atomic_class_type(right),
    string_representation(method, "equals"),
    string_representation(left, left_str),
    string_representation(right, right_str).
