.decl can_have_parentheses_fully_removed(id: id)
can_have_parentheses_fully_removed(id) :- method_invocation(id, _, _, _).
can_have_parentheses_fully_removed(id) :- method_invocation(_, _, _, [id, nil]).
can_have_parentheses_fully_removed(id) :- expression_name(id, _).
can_have_parentheses_fully_removed(id) :- return_statement(_, id).
can_have_parentheses_fully_removed(id) :- conditional_and_expression_unordered(_, id, _), equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- conditional_and_expression_unordered(_, id, _), not_equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- conditional_and_expression_unordered(_, id, _), less_than_or_equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- conditional_or_expression_unordered(_, id, _), equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- conditional_or_expression_unordered(_, id, _), not_equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- conditional_or_expression_unordered(_, id, _), less_than_or_equals_expression(id, _, _).
can_have_parentheses_fully_removed(id) :- if_statement(_, id, _, _).

rewrite("remove_redundant_parentheses", filename, start, end, content_str) :-
    can_have_parentheses_fully_removed(id),
    starts_at(id, start),
    ends_at(id, end),
    filename_of(id, filename),
    content_string_representation(id, content_str),
    string_representation(id, str),
    str != content_str.

rewrite("remove_redundant_parentheses", filename, start, end, cat("(", content_str, ")")) :-
    !can_have_parentheses_fully_removed(id),
    starts_at(id, start),
    ends_at(id, end),
    filename_of(id, filename),
    content_string_representation(id, content_str),
    string_representation(id, str),
    strlen(str) - strlen(content_str) >= 4.
